# defaults: &defaults
#   adapter: mysql2
#   pool: 5
#   username: myrailsbuddy
#   password: mypassusername: myrailsbuddy
#   password: mypass

development:
  database: menuapp_development
  host: localhost
  adapter: mysql2
  pool: 5
  username: myrailsbuddy
  password: mypass
